theme = "tokyonight"  # dark_plus works well with hx --tutor.

[editor]
mouse = false
end-of-line-diagnostics = "hint"
line-number = "relative"    # Displays line numbers relative to the current line
color-modes = true          # Enables different color modes based on the file type
auto-pairs = true           # Automatically inserts matching pairs
true-color = true           # Enables true color support
bufferline = "multiple"     # Displays multiple buffers in the buffer line
cursorline = true           # Highlights the current line
rulers = [200]              # Adds a visual ruler at column 200
auto-completion = true      # Enables auto-completion
completion-replace = true   # Replaces text with selected completion
completion-timeout = 3      # Sets the timeout for completions to 3 seconds
clipboard-provider = "termcode"
default-yank-register = "+"

[editor.indent-guides]
character = "╎"             # Character used for indentation guides
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
C-s = ":insert-output ruby $HOME/.config/hIDE/ai-connect/connect.rb inline -s %{cursor_line} %{cursor_column} %{buffer_name}"
esc = ["normal_mode", ":w"]

[keys.normal]
esc = ["collapse_selection", ":w"]
# Fix issues with my layout
"A-9" = "rotate_selection_contents_backward"
"A-0" = "rotate_selection_contents_forward"
"A-\\" = "shell_pipe_to"
"A-1" = "shell_append_output"

"L" = ":buffer-next"            # Next buffer (like :bn)
"H" = ":buffer-previous"        # Previous buffer (like :bp)
"Q" = ":buffer-close"           # Close buffer (like :bd)
"X" = ":buffer-close-others"    # Close other buffers (like :bd)
C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "jump_view_up"
C-j = "jump_view_down"
C-q = "wclose"

# Swap lines
S-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
S-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.normal.Z]
"Z" = ":xa" 

[keys.normal.space]
z = ":toggle gutters.line-numbers.min-width 3 35" 

[keys.normal.space.n]
h = [":sh zellij action new-pane --stacked -- hx", ":redraw"]
n = ":sh zellij action new-pane --direction Right"

[keys.select]
esc = ["collapse_selection", "normal_mode", ":w"]
# Fix issues with my layout
"A-9" = "rotate_selection_contents_backward"
"A-0" = "rotate_selection_contents_forward"
"A-\\" = "shell_pipe_to"
"A-1" = "shell_append_output"

C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "jump_view_up"
C-j = "jump_view_down"

# LSP Configuration
[editor.lsp]
enable = true               # Enables Language Server Protocol support
snippets = true             # Enables snippet support
auto-signature-help = true  # Automatically shows signature help
display-messages = true     # Displays messages from the language server

# File Picker Configuration
[editor.file-picker]
hidden = false

# Statusline Configuration
[editor.statusline]
left = ["mode", "file-modification-indicator", "spinner", "file-name"]
center = ["version-control"]
right = ["position", "position-percentage", "total-line-numbers", "file-type"]

# AI
[keys.normal."\\".a]
c = "@|ruby $HOME/.config/hIDE/ai-connect/connect.rb inline -c <C-r>%<ret>"
d = "@|ruby $HOME/.config/hIDE/ai-connect/connect.rb inline -dc <C-r>%<ret>"
i = "@|ruby $HOME/.config/hIDE/ai-connect/connect.rb inline <C-r>%<ret>"
[keys.select."\\".a]
c = "@|ruby $HOME/.config/hIDE/ai-connect/connect.rb inline -c <C-r>%<ret>"
d = "@|ruby $HOME/.config/hIDE/ai-connect/connect.rb inline -dc <C-r>%<ret>"
i = "@|ruby $HOME/.config/hIDE/ai-connect/connect.rb inline <C-r>%<ret>"


# filetree/ yazi
[keys.normal."\\".f]
e = ":sh $HOME/.config/hIDE/tools/picker.sh -i $ZELLIJ_PANE_ID -p ft"
y = ":sh $HOME/.config/hIDE/tools/picker.sh -i $ZELLIJ_PANE_ID -p yz"

[keys.normal."\\".g]
# project diff workspace in /tmp + filetree browser
d = ":sh $HOME/.config/hIDE/tools/git-diff.sh workspace $ZELLIJ_PANE_ID \"$PWD\""
D = "@:sh $HOME/.config/hIDE/tools/git-diff.sh workspace $ZELLIJ_PANE_ID \"$PWD\" "
# lazygit
l = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
b = ":sh git blame -L %{cursor_line},+1 %{buffer_name}"
